# Regression Analysis 
## analyzing regression to determine which factors produce the highest amount of ad clicks
### based on data from TravelPony Facebook adds

In [ ]:
## must download data from this link https://www.dropbox.com/s/4w7umic64h28j1z/nativeads.xls?dl=0

In [1]:
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 19 10:15:19 2018

@author: annie
"""
##PART 1 import dataset
import pandas as pd
tpony=pd.read_csv('travelponyfacebook.csv')
tpony['costperimpression']=tpony['Amount Spent (USD)']/tpony['Impressions']
import arrow 
import numpy as np

dayweek = []

for row in range(len(tpony)):
    date = arrow.get(tpony['Start Date'][row], 'M/D/YY')
    dayweek.append(date.isoweekday())
    
tpony['Day'] = dayweek

answer = tpony.groupby('Day')
answer.aggregate(np.mean)
print('THe least Expensive Day is Saturday (Day 6) ')
print ('THe Most Expensive Day or the day that works worst is Friday (Day 5)')

##PART 2
amtspentreach=np.corrcoef(tpony['Amount Spent (USD)'],tpony['Reach'])
print(amtspentreach)

amtspentfreq= np.corrcoef(tpony['Amount Spent (USD)'],tpony['Frequency'])
print(amtspentfreq)

amtspentfreq=np.corrcoef(tpony['Amount Spent (USD)'],tpony['Unique Clicks'])
print(amtspentfreq)

amtspentlikes=np.corrcoef(tpony['Amount Spent (USD)'],tpony['Page Likes'])
print(amtspentlikes)


import statsmodels.api as sm

y=tpony['Unique Clicks']
x=tpony [['Reach','Frequency']]

model=sm.OLS(y,x). fit()
predictions=model.predict(x)
print(model.summary())

print ('Frequency more strongly predicts unique clicks as the coefficient is much higher than that of the reach')





THe least Expensive Day is Saturday (Day 6) 
THe Most Expensive Day or the day that works worst is Friday (Day 5)
[[1.         0.70312381]
 [0.70312381 1.        ]]
[[1.         0.13020087]
 [0.13020087 1.        ]]
[[1.         0.88299318]
 [0.88299318 1.        ]]
[[1.         0.75761193]
 [0.75761193 1.        ]]
                            OLS Regression Results                            
Dep. Variable:          Unique Clicks   R-squared:                       0.557
Model:                            OLS   Adj. R-squared:                  0.556
Method:                 Least Squares   F-statistic:                     2325.
Date:                Thu, 18 Oct 2018   Prob (F-statistic):               0.00
Time:                        22:49:44   Log-Likelihood:                -15973.
No. Observations:                3705   AIC:                         3.195e+04
Df Residuals:                    3703   BIC:                         3.196e+04
Df Model:                           2             